name: CI (Windows)

on:
  push:
    branches:
    - develop
    - bobbrow/windowsCI
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true

      - script: 'node node_modules/vscode/bin/test'
        displayName: 'Run smoke tests'
        env:
          CODE_TESTS_PATH: '$(Build.SourcesDirectory)\out\test\smoke'
          CODE_TESTS_WORKSPACE: '$(Build.SourcesDirectory)\test\smoke'
